### ISSUE TITLE
Format to use when ORCIDs are stored in the EP database

### ISSUE THREAD

**Issue by MicheleMorelli** [eprints/orcid_support#11]
Hello,

According to the new ORCID guidance (https://support.orcid.org/knowledgebase/articles/116780):

> When stored, the ORCID iD should be expressed as a full https URI: https://orcid.org/xxxx-xxxx-xxxx-xxxx, complete with the protocol (https://), and with hyphens in the identifier (xxxx-xxxx-xxxx-xxxx).

This morning it was confirmed to me that also the Datacite schema (https://github.com/datacite/schema/issues/47) recommends to follow ORCID's indication above, i.e. using the https://orcid.org/xxxx-xxxx-xxxx-xxxx format, so I thought that it would be a good idea to discuss about it also here - (I saw that https://github.com/eprints/orcid_support/issues/6 raised by @jesusbagpuss was related to a similar topic).

I can see that the the https://orcid.org/xxxx-xxxx-xxxx-xxxx is already used to represent ORCIDs, but wanted to ask whether you think it would be a good idea to ensure that also the values in the DB are stored using the full https URI as ORCID is recommending?

Cheers,
Michele

**Comment by dennmuel** [comment]
Hi @MicheleMorelli,

just my two cents, in order to get the discussion going. Maybe @wfyson has more to say on this.

As far as displaying the orcid, I'd be fine with displaying them as https://orcid.org/xxxx-xxxx-xxxx-xxxx. The way the orcid is rendered seems to be rather easy to modify if necessary, e.g. for different kind of exports.

In the database, however, I'd stick to just the xxxx-xxxx-xxxx-xxxx format, because all other needed formats can be derived/assembled from that. If we had the full URL saved, we'd have to strip the url from everything but the id first, in order to do other stuff with it. Also I'm rather reluctant about changing already existing database values just to conform with a more or less arbitrary guideline that is potentially always subject to change.

Maybe as a compromise one could have another database field called `orcid_url` containing the full URL. However, I don't see the necessity for that.

Best regards
Dennis

**Comment by wfyson** [comment]
Hi @dennmuel , @MicheleMorelli 

I agree with Dennis with regards to this - storing the ORCIDS in the database using the xxxx-xxxx-xxxx-xxxx ormat seems to be the most flexible and effective way of storing them. I'd also vote against storing another database field called orcid_url as this would effectively be storing duplicate information, and EPrints is quite flexible with regards to rendering values anyway.

Many thanks,

Will
